using UnityEngine;

namespace Shenxiao.Framework.UI
{
    /// <summary>
    /// Base class for all view scripts attached to UI prefabs.
    /// Subclasses are typically the *Bind generated class which then has a partial business class.
    /// Lifecycle: BindNodes -> OnInit -> OnShow -> OnHide -> OnDispose.
    /// </summary>
    public abstract class BaseView : MonoBehaviour
    {
        /// <summary>UI layer this view belongs to. Override per view.</summary>
        public virtual UILayer Layer => UILayer.Window;

        public bool IsShown { get; private set; }
        public bool IsInitialized { get; private set; }

        internal void InternalInit()
        {
            if (IsInitialized) return;
            BindNodes();
            OnInit();
            IsInitialized = true;
        }

        internal void InternalShow(object args)
        {
            if (!IsInitialized) InternalInit();
            gameObject.SetActive(true);
            IsShown = true;
            OnShow(args);
        }

        internal void InternalHide()
        {
            if (!IsShown) return;
            OnHide();
            gameObject.SetActive(false);
            IsShown = false;
        }

        internal void InternalDispose()
        {
            OnDispose();
        }

        /// <summary>Auto-generated by the UI generator into the *Bind partial. Do not write by hand.</summary>
        protected virtual void BindNodes() { }

        /// <summary>Called once after BindNodes, before first Show.</summary>
        protected virtual void OnInit() { }

        /// <summary>Called every time the view is opened. args is the value passed to ViewManager.Open.</summary>
        protected virtual void OnShow(object args) { }

        /// <summary>Called when the view is closed (may be re-shown later).</summary>
        protected virtual void OnHide() { }

        /// <summary>Called when the view is destroyed. Release resources here.</summary>
        protected virtual void OnDispose() { }

        /// <summary>
        /// Null-check for generated Bind fields. References are assigned in the editor by the
        /// UI generator; a miss here means the prefab and the Bind script are out of sync.
        /// </summary>
        protected void EnsureBound(string fieldName, Object reference)
        {
            if (reference == null)
            {
                Debug.LogError($"[{GetType().Name}] Bind 字段未绑定: {fieldName}(重跑回填或检查节点是否被删)", this);
            }
        }
    }
}
