using System.Collections.Generic;
using UnityEngine;

namespace Shenxiao.Framework.UI
{
    /// <summary>
    /// Base class for all view scripts attached to UI prefabs.
    /// Subclasses are typically the *Bind generated class which then has a partial business class.
    /// Lifecycle: BindNodes -> OnInit -> OnShow -> OnHide -> OnDispose.
    /// </summary>
    public abstract class BaseView : MonoBehaviour
    {
        /// <summary>UI layer this view belongs to. Override per view.</summary>
        public virtual UILayer Layer => UILayer.Window;

        public bool IsShown { get; private set; }
        public bool IsInitialized { get; private set; }

        internal void InternalInit()
        {
            if (IsInitialized) return;
            BindNodes();
            OnInit();
            IsInitialized = true;
        }

        /// <summary>
        /// 公开的显示/隐藏入口,给"模块合并 prefab"内由业务流程直接管理的子窗口用
        /// (独立 prefab 窗口仍走 ViewManager.Open/Close)。
        /// Show 会把窗口置顶:模块内窗口按转换时的字母序排列,弹窗(如协议提示)
        /// 不置顶会被后面的全屏窗口盖住。
        /// </summary>
        public void Show(object args = null)
        {
            transform.SetAsLastSibling();
            InternalShow(args);
        }

        public void Hide() => InternalHide();

        internal void InternalShow(object args)
        {
            if (!IsInitialized) InternalInit();
            gameObject.SetActive(true);
            IsShown = true;
            OnShow(args);
        }

        internal void InternalHide()
        {
            if (!IsShown) return;
            OnHide();
            gameObject.SetActive(false);
            IsShown = false;
        }

        internal void InternalDispose()
        {
            OnDispose();
        }

        /// <summary>Auto-generated by the UI generator into the *Bind partial. Do not write by hand.</summary>
        protected virtual void BindNodes() { }

        /// <summary>Called once after BindNodes, before first Show.</summary>
        protected virtual void OnInit() { }

        /// <summary>Called every time the view is opened. args is the value passed to ViewManager.Open.</summary>
        protected virtual void OnShow(object args) { }

        /// <summary>Called when the view is closed (may be re-shown later).</summary>
        protected virtual void OnHide() { }

        /// <summary>Called when the view is destroyed. Release resources here.</summary>
        protected virtual void OnDispose() { }

        /// <summary>
        /// Null-check for generated Bind fields. References are assigned in the editor by the
        /// UI generator; a miss here means the prefab and the Bind script are out of sync.
        /// </summary>
        private static readonly HashSet<string> s_tplMissLogged = new HashSet<string>();

        protected void EnsureBound(string fieldName, Object reference)
        {
            if (reference != null) return;
            // _tpl_* 是烤制时被裁掉的 inactive 模板节点(运行时消费方均有 null 兜底),
            // 每次开界面都报 Error 只是噪音——降为全局一次性提示。
            if (fieldName.StartsWith("_tpl_", System.StringComparison.Ordinal))
            {
                if (s_tplMissLogged.Add($"{GetType().Name}.{fieldName}"))
                    Debug.LogWarning($"[{GetType().Name}] 模板字段未回填(烤制裁剪,已知家族): {fieldName} — 需要该模板时重跑 UiCreator 回填", this);
                return;
            }
            Debug.LogError($"[{GetType().Name}] Bind 字段未绑定: {fieldName}(重跑回填或检查节点是否被删)", this);
        }
    }
}
