<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <BaseOutputPath>artifacts/bin/</BaseOutputPath>
    <NoWarn>CS0436</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../../Assets/Scripts/Module/Core/DungeonHeart/**/*.cs" LinkBase="DungeonHeart" />
    <Reference Include="UnityEngine.CoreModule"><HintPath>C:/Program Files/Unity/Hub/Editor/6000.3.17f1/Editor/Data/Managed/UnityEngine/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>../../../../Library/ScriptAssemblies/UnityEngine.UI.dll</HintPath></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>../../../../Library/ScriptAssemblies/Unity.TextMeshPro.dll</HintPath></Reference>
    <Reference Include="Shenxiao.Framework"><HintPath>../../../../Library/ScriptAssemblies/Shenxiao.Framework.dll</HintPath></Reference>
    <Reference Include="Shenxiao.Generated"><HintPath>../../../../Library/ScriptAssemblies/Shenxiao.Generated.dll</HintPath></Reference>
    <Reference Include="Shenxiao.Common"><HintPath>../../../../Library/ScriptAssemblies/Shenxiao.Common.dll</HintPath></Reference>
    <Reference Include="Shenxiao.Module.Core"><HintPath>../../../../Library/ScriptAssemblies/Shenxiao.Module.Core.dll</HintPath></Reference>
  </ItemGroup>
</Project>
