namespace Shenxiao.Framework.Config
{
    /// <summary>
    /// Base class for config Vo types generated by ConfigGenerator.
    /// Generated classes derive from this; do not edit generated files.
    /// </summary>
    public abstract class BaseVo
    {
    }
}
