using System.Threading.Tasks;
using UnityEngine;
using Shenxiao.Framework.Res;

namespace Shenxiao.Framework.Config
{
    /// <summary>
    /// Generic config table loading helpers.
    /// Concrete table loaders (ConfigSkill, ConfigEquip ...) are generated by ConfigGenerator
    /// and use these helpers internally.
    /// </summary>
    public static class ConfigManager
    {
        /// <summary>
        /// Load a JSON config file as raw text via Addressables.
        /// </summary>
        public static async Task<string> LoadJsonText(string addrKey)
        {
            var asset = await ResManager.LoadAsync<TextAsset>(addrKey);
            return asset != null ? asset.text : null;
        }
    }
}
