'use strict';

const TOOL_NAME = '@shenxiao/ui-audit';
const TOOL_VERSION = '1.2.1';
const ROUTE_SCHEMA_VERSION = 1;
const REPORT_SCHEMA_VERSION = 1;
const RUNTIME_NODE_SCHEMA_VERSION = 3;
const CANVAS_INPUT_SCHEMA_VERSION = 1;
const RUNTIME_OVERLAY_POLICY_SCHEMA_VERSION = 1;
const POPUP_POLICY_SCHEMA_VERSION = 1;
const PROTOCOL_POLICY_SCHEMA_VERSION = 2;
const SERVER_PROFILE_SCHEMA_VERSION = 1;
const PROTOCOL_TRACE_SCHEMA_VERSION = 3;
const SERVER_OBSERVATION_SCHEMA_VERSION = 1;
const RESOURCE_TOOL_PREVIEW_SCHEMA_VERSION = 1;
const COMPLETED_SCOPE_POLICY_SCHEMA_VERSION = 1;

function versionInfo() {
  return {
    tool: TOOL_NAME,
    version: TOOL_VERSION,
    schemas: {
      route: ROUTE_SCHEMA_VERSION,
      report: REPORT_SCHEMA_VERSION,
      runtimeNode: RUNTIME_NODE_SCHEMA_VERSION,
      canvasInput: CANVAS_INPUT_SCHEMA_VERSION,
      runtimeOverlayPolicy: RUNTIME_OVERLAY_POLICY_SCHEMA_VERSION,
      popupPolicy: POPUP_POLICY_SCHEMA_VERSION,
      protocolPolicy: PROTOCOL_POLICY_SCHEMA_VERSION,
      serverProfile: SERVER_PROFILE_SCHEMA_VERSION,
      protocolTrace: PROTOCOL_TRACE_SCHEMA_VERSION,
      serverObservation: SERVER_OBSERVATION_SCHEMA_VERSION,
      resourceToolPreview: RESOURCE_TOOL_PREVIEW_SCHEMA_VERSION,
      completedScopePolicy: COMPLETED_SCOPE_POLICY_SCHEMA_VERSION,
    },
  };
}

module.exports = {
  TOOL_NAME,
  TOOL_VERSION,
  ROUTE_SCHEMA_VERSION,
  REPORT_SCHEMA_VERSION,
  RUNTIME_NODE_SCHEMA_VERSION,
  CANVAS_INPUT_SCHEMA_VERSION,
  RUNTIME_OVERLAY_POLICY_SCHEMA_VERSION,
  POPUP_POLICY_SCHEMA_VERSION,
  PROTOCOL_POLICY_SCHEMA_VERSION,
  SERVER_PROFILE_SCHEMA_VERSION,
  PROTOCOL_TRACE_SCHEMA_VERSION,
  SERVER_OBSERVATION_SCHEMA_VERSION,
  RESOURCE_TOOL_PREVIEW_SCHEMA_VERSION,
  COMPLETED_SCOPE_POLICY_SCHEMA_VERSION,
  versionInfo,
};
