using System; using System.Collections; using System.Collections.Generic; using System.Reflection; using System.Threading.Tasks;
using Shenxiao.Framework.Net; using Shenxiao.Module.Core.Demon; using UnityEngine;
namespace Shenxiao.EditorTools
{
    public static class DemonCase
    {
        private const BindingFlags F = BindingFlags.NonPublic | BindingFlags.Instance; private const BindingFlags SF = BindingFlags.NonPublic | BindingFlags.Static;
        public static Task<int> Run() { try { return Task.FromResult(RunSync()); } catch (Exception e) { Debug.LogError("CLIVERIFY demon EXCEPTION " + e); return Task.FromResult(3); } }
        private static int RunSync()
        {
            DemonController c = DemonController.Instance; DemonModel m = DemonModel.Instance; FieldInfo fi = typeof(DemonController).GetField("s_outboundIntercept", SF); var ambient = new Ambient(c, m, fi); bool pass = false, restored = false;
            try
            {
                c.Init(); m.Reset(); MethodInfo on = typeof(DemonController).GetMethod("On18301", F); MethodInfo onFetters = typeof(DemonController).GetMethod("On18303", F); MethodInfo onPaintings = typeof(DemonController).GetMethod("On18307", F); MethodInfo onBlessing = typeof(DemonController).GetMethod("On50901", F); MethodInfo onShop = typeof(DemonController).GetMethod("On18311", F); var h = typeof(NetManager).GetField("_handlers", SF)?.GetValue(null) as IDictionary; bool seams = fi != null && on != null && onFetters != null && onPaintings != null && onBlessing != null && onShop != null && h != null && h.Contains(Proto.DEMON_INFO) && h.Contains(Proto.DEMON_POWER) && h.Contains(Proto.DEMON_FETTERS) && h.Contains(Proto.DEMON_PAINTINGS) && h.Contains(Proto.DEMON_BLESSING) && h.Contains(Proto.DEMON_TALENT_SHOP) && h.Contains(Proto.DEMON_TALENT_POWER) && !h.Contains(50902) && !h.Contains(18312) && !h.Contains(18313) && !h.Contains(18315); pass = seams; for (int id = 18304; id <= 18306; id++) pass &= !h.Contains(id); for (int id = 18308; id <= 18317; id++) if (id != 18311 && id != 18314) pass &= !h.Contains(id); void Check(string tag, bool ok) { Debug.Log("CLIVERIFY demon " + tag + " ok=" + ok); if (!ok) pass = false; } Check("seams/register", pass); if (!pass) throw new InvalidOperationException("demon seams missing");
                var frames = new List<byte[]>(); fi.SetValue(null, new Func<byte[], bool>(f => { frames.Add(f); return true; })); c.RequestStartup(); Check("startup exact empty frames", Frames(frames, Proto.DEMON_INFO, Proto.DEMON_FETTERS, Proto.DEMON_PAINTINGS, Proto.DEMON_BLESSING)); frames.Clear();
                c.RequestTalentShop(); Check("18311 exact empty frame", Frames(frames, Proto.DEMON_TALENT_SHOP) && !m.HasTalentShopSnapshot); frames.Clear();
                byte[] first = new CliVerify.Pkt().C(2).H(2)
                    .I(101).H(11).I(4000000000L).C(3).C(4).H(2).I(501).H(1).I(4000000000L).C(1).I(502).H(2).I(3).C(0).H(2).I(601).H(4).C(2).C(5).H(6).I(602).H(7).C(8).C(9).H(10)
                    .I(102).H(12).I(0).C(0).C(0).H(0).H(0).Bytes(); var r1 = new NetReader(first, 0, first.Length); on.Invoke(c, new object[] { r1 }); m.TryGet(101, out DemonModel.Entry one); m.TryGet(102, out DemonModel.Entry two);
                Check("two entities/all fields/order/read-to-end", r1.Remaining == 0 && m.HasData && m.OpenState == 2 && m.Demons.Count == 2 && one != null && one.Level == 11 && one.Experience == 4000000000U && one.Star == 3 && one.SlotNumber == 4 && one.Skills.Count == 2 && one.Skills[0].SkillId == 501 && one.Skills[0].SkillLevel == 1 && one.Skills[0].Process == 4000000000U && one.Skills[0].IsActive == 1 && one.Skills[1].SkillId == 502 && one.Skills[1].SkillLevel == 2 && one.Skills[1].Process == 3 && one.Skills[1].IsActive == 0 && one.SlotSkills.Count == 2 && one.SlotSkills[0].SkillId == 601 && one.SlotSkills[0].SkillLevel == 4 && one.SlotSkills[0].Slot == 2 && one.SlotSkills[0].Quality == 5 && one.SlotSkills[0].Sort == 6 && one.SlotSkills[1].SkillId == 602 && one.SlotSkills[1].SkillLevel == 7 && one.SlotSkills[1].Slot == 8 && one.SlotSkills[1].Quality == 9 && one.SlotSkills[1].Sort == 10 && two != null && two.Level == 12 && two.Skills.Count == 0 && two.SlotSkills.Count == 0 && frames.Count == 0);
                byte[] second = new CliVerify.Pkt().C(1).H(1).I(103).H(13).I(4).C(5).C(6).H(0).H(0).Bytes(); var r2 = new NetReader(second, 0, second.Length); on.Invoke(c, new object[] { r2 }); Check("whole replace removes old", r2.Remaining == 0 && m.Demons.Count == 1 && m.TryGet(103, out DemonModel.Entry three) && three.Level == 13 && three.Experience == 4 && !m.TryGet(101, out _) && !m.TryGet(102, out _) && frames.Count == 0);
                byte[] empty = new CliVerify.Pkt().C(0).H(0).Bytes(); var r3 = new NetReader(empty, 0, empty.Length); on.Invoke(c, new object[] { r3 }); Check("empty replace clears old", r3.Remaining == 0 && m.HasData && m.OpenState == 0 && m.Demons.Count == 0 && frames.Count == 0);
                byte[] fetters = new CliVerify.Pkt().H(4).I(11).I(4000000000L).I(11).I(12).Bytes(); var f1 = new NetReader(fetters, 0, fetters.Length); onFetters.Invoke(c, new object[] { f1 }); Check("fetters dedupe/read-to-end/no-outbound", f1.Remaining == 0 && m.HasFettersData && m.Fetters.Count == 3 && m.Fetters[0] == 11 && m.Fetters[1] == 4000000000U && m.Fetters[2] == 12 && m.HasFetter(4000000000U) && frames.Count == 0);
                byte[] fettersSecond = new CliVerify.Pkt().H(1).I(13).Bytes(); var f2 = new NetReader(fettersSecond, 0, fettersSecond.Length); onFetters.Invoke(c, new object[] { f2 }); Check("fetters whole replace", f2.Remaining == 0 && m.Fetters.Count == 1 && m.HasFetter(13) && !m.HasFetter(11) && frames.Count == 0);
                byte[] fettersEmpty = new CliVerify.Pkt().H(0).Bytes(); var f3 = new NetReader(fettersEmpty, 0, fettersEmpty.Length); onFetters.Invoke(c, new object[] { f3 }); Check("fetters empty replaces", f3.Remaining == 0 && m.HasFettersData && m.Fetters.Count == 0 && frames.Count == 0);
                byte[] paintings = new CliVerify.Pkt().H(5).C(0).C(255).C(0).C(7).C(255).Bytes(); var p1 = new NetReader(paintings, 0, paintings.Length); onPaintings.Invoke(c, new object[] { p1 }); Check("paintings dedupe/read-to-end/no-outbound", p1.Remaining == 0 && m.HasPaintingsData && m.Paintings.Count == 3 && m.Paintings[0] == 0 && m.Paintings[1] == 255 && m.Paintings[2] == 7 && m.HasPainting(255) && frames.Count == 0);
                byte[] paintingsSecond = new CliVerify.Pkt().H(1).C(8).Bytes(); var p2 = new NetReader(paintingsSecond, 0, paintingsSecond.Length); onPaintings.Invoke(c, new object[] { p2 }); Check("paintings whole replace", p2.Remaining == 0 && m.Paintings.Count == 1 && m.HasPainting(8) && !m.HasPainting(255) && frames.Count == 0);
                byte[] paintingsEmpty = new CliVerify.Pkt().H(0).Bytes(); var p3 = new NetReader(paintingsEmpty, 0, paintingsEmpty.Length); onPaintings.Invoke(c, new object[] { p3 }); Check("paintings empty replaces", p3.Remaining == 0 && m.HasPaintingsData && m.Paintings.Count == 0 && frames.Count == 0);
                byte[] blessing = new CliVerify.Pkt().I(4000000000L).Bytes(); var b1 = new NetReader(blessing, 0, blessing.Length); onBlessing.Invoke(c, new object[] { b1 }); Check("blessing/read-to-end/no-outbound", b1.Remaining == 0 && m.HasBlessingData && m.BlessingValue == 4000000000U && frames.Count == 0);
                byte[] blessingSecond = new CliVerify.Pkt().I(7).Bytes(); var b2 = new NetReader(blessingSecond, 0, blessingSecond.Length); onBlessing.Invoke(c, new object[] { b2 }); Check("blessing scalar replace", b2.Remaining == 0 && m.HasBlessingData && m.BlessingValue == 7 && frames.Count == 0);
                var s0b = ShopPacket(0, 0, new ObjectSpec[0], new ShopSpec[0]); var s0 = new NetReader(s0b, 0, s0b.Length); onShop.Invoke(c, new object[] { s0 }); Check("18311 empty replaces", s0.Remaining == 0 && m.HasTalentShopSnapshot && m.TalentShopRefreshTime == 0 && m.TalentShopRefreshNum == 0 && m.TalentShopCost.Count == 0 && m.TalentShop.Count == 0 && frames.Count == 0);
                ObjectSpec duplicate = new ObjectSpec(255, uint.MaxValue, uint.MaxValue); ObjectSpec otherCost = new ObjectSpec(0, 1, 2);
                ShopSpec firstShop = new ShopSpec(uint.MaxValue, 4, 5, 6, 7, 8, 9, 10); ShopSpec secondShop = new ShopSpec(uint.MaxValue, uint.MaxValue, uint.MaxValue, ushort.MaxValue, ushort.MaxValue, byte.MaxValue, ushort.MaxValue, ushort.MaxValue);
                var smanyb = ShopPacket(uint.MaxValue, ushort.MaxValue, new[] { duplicate, otherCost }, new[] { firstShop, secondShop }); var smany = new NetReader(smanyb, 0, smanyb.Length); onShop.Invoke(c, new object[] { smany }); Check("18311 all fields/order/duplicates", smany.Remaining == 0 && m.TalentShopRefreshTime == uint.MaxValue && m.TalentShopRefreshNum == ushort.MaxValue && m.TalentShopCost.Count == 2 && Eq(m.TalentShopCost[0], duplicate) && Eq(m.TalentShopCost[1], otherCost) && m.TalentShop.Count == 2 && Eq(m.TalentShop[0], firstShop) && Eq(m.TalentShop[1], secondShop) && frames.Count == 0);
                c.RequestTalentShop(); Check("18311 no response keeps state", Frames(frames, Proto.DEMON_TALENT_SHOP) && m.TalentShop.Count == 2 && m.TalentShop[0].Id == uint.MaxValue); frames.Clear();
                byte[] isoDemon = new CliVerify.Pkt().C(1).H(0).Bytes(); var isoD = new NetReader(isoDemon, 0, isoDemon.Length); on.Invoke(c, new object[] { isoD }); byte[] isoFetter = new CliVerify.Pkt().H(1).I(1).Bytes(); var isoF = new NetReader(isoFetter, 0, isoFetter.Length); onFetters.Invoke(c, new object[] { isoF }); byte[] isoPainting = new CliVerify.Pkt().H(1).C(1).Bytes(); var isoP = new NetReader(isoPainting, 0, isoPainting.Length); onPaintings.Invoke(c, new object[] { isoP }); byte[] isoBlessing = new CliVerify.Pkt().I(1).Bytes(); var isoB = new NetReader(isoBlessing, 0, isoBlessing.Length); onBlessing.Invoke(c, new object[] { isoB }); Check("other snapshots retain 18311", isoD.Remaining == 0 && isoF.Remaining == 0 && isoP.Remaining == 0 && isoB.Remaining == 0 && m.TalentShop.Count == 2 && m.TalentShop[0].Id == uint.MaxValue && m.TalentShop[0].GoodsId == 4 && m.TalentShop[1].Id == uint.MaxValue && frames.Count == 0);
                var slessb = ShopPacket(11, 12, new[] { new ObjectSpec(13, 14, 15) }, new[] { new ShopSpec(16, 17, 18, 19, 20, 21, 22, 23) }); var sless = new NetReader(slessb, 0, slessb.Length); onShop.Invoke(c, new object[] { sless }); Check("18311 full replace/isolation", sless.Remaining == 0 && m.TalentShopRefreshTime == 11 && m.TalentShopRefreshNum == 12 && m.TalentShopCost.Count == 1 && m.TalentShop.Count == 1 && m.TalentShop[0].Id == 16 && m.HasData && m.HasFettersData && m.HasPaintingsData && m.HasBlessingData && frames.Count == 0);
                var sclearb = ShopPacket(0, 0, new ObjectSpec[0], new ShopSpec[0]); var sclear = new NetReader(sclearb, 0, sclearb.Length); onShop.Invoke(c, new object[] { sclear }); Check("18311 empty clears", sclear.Remaining == 0 && m.HasTalentShopSnapshot && m.TalentShopCost.Count == 0 && m.TalentShop.Count == 0 && frames.Count == 0);
                c.Dispose(); Check("dispose reset", !c.IsInitialized && !m.HasData && !m.HasFettersData && !m.HasPaintingsData && !m.HasBlessingData && !m.HasTalentShopSnapshot && m.DemonPowerCount == 0 && m.OpenState == 0 && m.BlessingValue == 0 && m.Demons.Count == 0 && m.Fetters.Count == 0 && m.Paintings.Count == 0 && m.TalentShop.Count == 0); Debug.Log("CLIVERIFY demon VERDICT pass=" + pass);
            }
            finally { restored = ambient.Restore(c, m, fi); Debug.Log("CLIVERIFY demon restored=" + restored + " pass=" + pass); }
            return pass && restored ? 0 : 3;
        }
        private static bool Frames(IReadOnlyList<byte[]> frames, params int[] ids) { if (frames.Count != ids.Length) return false; for (int i = 0; i < ids.Length; i++) { byte[] f = frames[i]; if (f == null || f.Length != 6 || f[0] != 0 || f[1] != 6 || f[2] != 3 || f[3] != 232 || f[4] != (byte)(ids[i] >> 8) || f[5] != (byte)(ids[i] & 0xFF)) return false; } return true; }
        private static byte[] ShopPacket(uint refreshTime, ushort refreshNum, ObjectSpec[] cost, ShopSpec[] shop) { var p = new CliVerify.Pkt().I(refreshTime).H(refreshNum).H(cost.Length); foreach (ObjectSpec o in cost) p.C(o.Style).I(o.TypeId).I(o.Count); p.H(shop.Length); foreach (ShopSpec s in shop) p.I(s.Id).I(s.GoodsId).I(s.Price).H(s.Num).H(s.CostNum).C(s.Discount).H(s.CanBuyNum).H(s.BuyNum); return p.Bytes(); }
        private static bool Eq(DemonModel.ObjectEntry a, ObjectSpec b) => a.Style == b.Style && a.TypeId == b.TypeId && a.Count == b.Count;
        private static bool Eq(DemonModel.TalentShopEntry a, ShopSpec b) => a.Id == b.Id && a.GoodsId == b.GoodsId && a.Price == b.Price && a.Num == b.Num && a.CostNum == b.CostNum && a.Discount == b.Discount && a.CanBuyNum == b.CanBuyNum && a.BuyNum == b.BuyNum;
        private struct ObjectSpec { public readonly byte Style; public readonly uint TypeId; public readonly uint Count; public ObjectSpec(byte style, uint typeId, uint count) { Style = style; TypeId = typeId; Count = count; } }
        private struct ShopSpec { public readonly uint Id; public readonly uint GoodsId; public readonly uint Price; public readonly ushort Num; public readonly ushort CostNum; public readonly byte Discount; public readonly ushort CanBuyNum; public readonly ushort BuyNum; public ShopSpec(uint id, uint goodsId, uint price, ushort num, ushort costNum, byte discount, ushort canBuyNum, ushort buyNum) { Id = id; GoodsId = goodsId; Price = price; Num = num; CostNum = costNum; Discount = discount; CanBuyNum = canBuyNum; BuyNum = buyNum; } }

        private sealed class Ambient
        {
            private static readonly int[] P = { 18301, 18302, 18303, 18307, 18311, 18314, 50901 };
            private readonly bool _init, _has, _fettersLoaded, _paintingsLoaded, _blessingLoaded, _shopLoaded; private readonly byte _open; private readonly uint _blessing, _refresh; private readonly ushort _refreshNum; private readonly object _intercept; private readonly Dictionary<int, object> _handlers = new Dictionary<int, object>(); private readonly List<DemonModel.Entry> _entries; private readonly List<uint> _fetters; private readonly List<byte> _paintings; private readonly List<DemonModel.ObjectEntry> _cost; private readonly List<DemonModel.TalentShopEntry> _shop; private readonly Dictionary<uint, uint> _power; private readonly Dictionary<string, DemonModel.TalentPower> _demonTalent, _goodsTalent;
            public Ambient(DemonController c, DemonModel m, FieldInfo intercept) { _init = c.IsInitialized; _has = m.HasData; _fettersLoaded = m.HasFettersData; _paintingsLoaded = m.HasPaintingsData; _blessingLoaded = m.HasBlessingData; _shopLoaded = m.HasTalentShopSnapshot; _open = m.OpenState; _blessing = m.BlessingValue; _refresh = m.TalentShopRefreshTime; _refreshNum = m.TalentShopRefreshNum; _entries = new List<DemonModel.Entry>(m.Demons); _fetters = new List<uint>(m.Fetters); _paintings = new List<byte>(m.Paintings); _cost = new List<DemonModel.ObjectEntry>(m.TalentShopCost); _shop = new List<DemonModel.TalentShopEntry>(m.TalentShop); _intercept = intercept == null ? null : intercept.GetValue(null); _power = Copy<uint, uint>(m, "_demonPower"); _demonTalent = Copy<string, DemonModel.TalentPower>(m, "_demonTalentPower"); _goodsTalent = Copy<string, DemonModel.TalentPower>(m, "_goodsTalentPower"); IDictionary h = typeof(NetManager).GetField("_handlers", SF)?.GetValue(null) as IDictionary; if (h != null) foreach (int id in P) if (h.Contains(id)) _handlers[id] = h[id]; }
            public bool Restore(DemonController c, DemonModel m, FieldInfo intercept) { try { if (c.IsInitialized) c.Dispose(); m.Reset(); if (_has) m.Replace(_open, _entries); if (_fettersLoaded) m.ReplaceFetters(_fetters); if (_paintingsLoaded) m.ReplacePaintings(_paintings); if (_blessingLoaded) m.ReplaceBlessing(_blessing); if (_shopLoaded) m.ReplaceTalentShop(_refresh, _refreshNum, _cost, _shop); Put(m, "_demonPower", _power); Put(m, "_demonTalentPower", _demonTalent); Put(m, "_goodsTalentPower", _goodsTalent); if (_init) c.Init(); IDictionary h = typeof(NetManager).GetField("_handlers", SF)?.GetValue(null) as IDictionary; if (h == null) return false; foreach (int id in P) if (_handlers.TryGetValue(id, out object value)) h[id] = value; else h.Remove(id); if (intercept != null) intercept.SetValue(null, _intercept); if (c.IsInitialized != _init || m.HasData != _has || m.HasFettersData != _fettersLoaded || m.HasPaintingsData != _paintingsLoaded || m.HasBlessingData != _blessingLoaded || m.HasTalentShopSnapshot != _shopLoaded || m.OpenState != _open || m.BlessingValue != _blessing || m.TalentShopRefreshTime != _refresh || m.TalentShopRefreshNum != _refreshNum || !Same(m.Demons, _entries) || !Same(m.Fetters, _fetters) || !Same(m.Paintings, _paintings) || !Same(m.TalentShopCost, _cost) || !Same(m.TalentShop, _shop) || !SameDictionary(m, "_demonPower", _power) || !SameDictionary(m, "_demonTalentPower", _demonTalent) || !SameDictionary(m, "_goodsTalentPower", _goodsTalent) || (intercept != null && !ReferenceEquals(intercept.GetValue(null), _intercept))) return false; foreach (int id in P) { bool existed = _handlers.TryGetValue(id, out object expected); if (h.Contains(id) != existed || (existed && !ReferenceEquals(h[id], expected))) return false; } return true; } catch (Exception e) { Debug.LogError("CLIVERIFY demon restore " + e); return false; } }
            private static Dictionary<TKey, TValue> Copy<TKey, TValue>(DemonModel m, string field) => new Dictionary<TKey, TValue>((Dictionary<TKey, TValue>)typeof(DemonModel).GetField(field, F).GetValue(m));
            private static void Put<TKey, TValue>(DemonModel m, string field, Dictionary<TKey, TValue> values) { var target = (Dictionary<TKey, TValue>)typeof(DemonModel).GetField(field, F).GetValue(m); target.Clear(); foreach (var pair in values) target[pair.Key] = pair.Value; }
            private static bool Same<T>(IReadOnlyList<T> actual, List<T> expected) { if (actual.Count != expected.Count) return false; for (int i = 0; i < actual.Count; i++) if (!EqualityComparer<T>.Default.Equals(actual[i], expected[i])) return false; return true; }
            private static bool SameDictionary<TKey, TValue>(DemonModel m, string field, Dictionary<TKey, TValue> expected) { var actual = (Dictionary<TKey, TValue>)typeof(DemonModel).GetField(field, F).GetValue(m); if (actual.Count != expected.Count) return false; foreach (var pair in expected) if (!actual.TryGetValue(pair.Key, out TValue value) || !EqualityComparer<TValue>.Default.Equals(value, pair.Value)) return false; return true; }
        }
    }
}
