using System; using System.Collections; using System.Collections.Generic; using System.Reflection; using System.Threading.Tasks; using Shenxiao.Framework.Net; using Shenxiao.Module.Core.Revelation; using UnityEngine;
namespace Shenxiao.EditorTools
{
    public static class RevelationCase
    {
        private const BindingFlags F = BindingFlags.NonPublic | BindingFlags.Instance, SF = BindingFlags.NonPublic | BindingFlags.Static;
        public static Task<int> Run() { try { return Task.FromResult(RunSync()); } catch (Exception e) { Debug.LogError("CLIVERIFY revelation EXCEPTION " + e); return Task.FromResult(3); } }
        private static int RunSync()
        {
            RevelationController c = RevelationController.Instance; RevelationModel m = RevelationModel.Instance; bool was = c.IsInitialized, oldHas = m.HasData; ushort oldMax = m.MaxFigureId, oldCurrent = m.CurrentFigureId; ulong oldPower = m.Power; var og = new List<RevelationModel.Gathering>(m.Gatherings); var os = new List<RevelationModel.Suit>(m.Suits); var ok = new List<RevelationModel.Skill>(m.Skills); FieldInfo fi = typeof(RevelationController).GetField("s_outboundIntercept", SF); object oldIntercept = fi?.GetValue(null);
            try { c.Init(); m.Reset(); MethodInfo on = typeof(RevelationController).GetMethod("On28606", F); MethodInfo power = typeof(RevelationController).GetMethod("On28609", F); var h = typeof(NetManager).GetField("_handlers", SF)?.GetValue(null) as IDictionary; bool pass = fi != null && on != null && power != null && h != null && h.Contains(Proto.REVELATION_INFO) && h.Contains(Proto.REVELATION_POWER); for (int id = 28600; id <= 28609; id++) if (id != 28606 && id != 28609) pass &= !h.Contains(id); void Check(string t, bool v) { Debug.Log("CLIVERIFY revelation " + t + " ok=" + v); if (!v) pass = false; } Check("seams/register", pass); if (!pass) return 3;
                var frames = new List<byte[]>(); fi.SetValue(null, new Func<byte[], bool>(x => { frames.Add(x); return true; })); c.RequestStartup(); Check("startup exact empty frame", Frame(frames, Proto.REVELATION_INFO)); frames.Clear(); c.RequestPower(); Check("power exact empty frame", Frame(frames, Proto.REVELATION_POWER)); frames.Clear(); byte[] pre = new CliVerify.Pkt().L(5000000001L).Bytes(); var pr = new NetReader(pre, 0, pre.Length); power.Invoke(c, new object[] { pr }); Check("preload power ignored", pr.Remaining == 0 && !m.HasData && m.Power == 0 && frames.Count == 0);
                byte[] first = new CliVerify.Pkt().H(65535).H(65534).L(5000000000L).H(2).C(0).H(65535).I(4000000000L).C(255).C(255).H(1).I(2).C(0).H(2).I(4000000000L).I(3).I(4).I(5).H(2).I(6).H(65535).I(7).H(1).Bytes(); var r = new NetReader(first, 0, first.Length); on.Invoke(c, new object[] { r }); Check("fields/order/read-to-end/no-outbound", r.Remaining == 0 && m.HasData && m.MaxFigureId == 65535 && m.CurrentFigureId == 65534 && m.Power == 5000000000UL && m.Gatherings.Count == 2 && m.Gatherings[0].Pos == 0 && m.Gatherings[0].Level == 65535 && m.Gatherings[0].Experience == 4000000000U && m.Gatherings[0].Flag == 255 && m.Gatherings[1].Pos == 255 && m.Gatherings[1].Level == 1 && m.Gatherings[1].Experience == 2 && m.Gatherings[1].Flag == 0 && m.Suits.Count == 2 && m.Suits[0].Star == 4000000000U && m.Suits[0].Number == 3 && m.Suits[1].Star == 4 && m.Suits[1].Number == 5 && m.Skills.Count == 2 && m.Skills[0].SkillId == 6 && m.Skills[0].Level == 65535 && m.Skills[1].SkillId == 7 && m.Skills[1].Level == 1 && frames.Count == 0);
                var loadedPowerReader = new NetReader(new CliVerify.Pkt().L(5000000001L).Bytes(), 0, 8); power.Invoke(c, new object[] { loadedPowerReader }); Check("power loaded replace", loadedPowerReader.Remaining == 0 && m.Power == 5000000001UL && m.MaxFigureId == 65535 && m.CurrentFigureId == 65534 && m.Gatherings.Count == 2 && m.Suits.Count == 2 && m.Skills.Count == 2 && frames.Count == 0); var loadedMaxReader = new NetReader(new CliVerify.Pkt().L(unchecked((long)ulong.MaxValue)).Bytes(), 0, 8); power.Invoke(c, new object[] { loadedMaxReader }); Check("power u64 max", loadedMaxReader.Remaining == 0 && m.Power == ulong.MaxValue && m.MaxFigureId == 65535 && m.CurrentFigureId == 65534 && m.Gatherings.Count == 2 && m.Suits.Count == 2 && m.Skills.Count == 2 && frames.Count == 0);
                byte[] empty = new CliVerify.Pkt().H(2).H(1).L(7).H(0).H(0).H(0).Bytes(); var e = new NetReader(empty, 0, empty.Length); on.Invoke(c, new object[] { e }); Check("whole replace empty lists", e.Remaining == 0 && m.MaxFigureId == 2 && m.CurrentFigureId == 1 && m.Power == 7 && m.Gatherings.Count == 0 && m.Suits.Count == 0 && m.Skills.Count == 0 && frames.Count == 0);
                c.Dispose(); Check("dispose reset", !c.IsInitialized && !m.HasData && m.MaxFigureId == 0 && m.CurrentFigureId == 0 && m.Power == 0 && m.Gatherings.Count == 0 && m.Suits.Count == 0 && m.Skills.Count == 0); Debug.Log("CLIVERIFY revelation VERDICT pass=" + pass); return pass ? 0 : 3; }
            finally { if (c.IsInitialized) c.Dispose(); m.Reset(); if (oldHas) m.Replace(oldMax, oldCurrent, oldPower, og, os, ok); if (was) c.Init(); if (fi != null) fi.SetValue(null, oldIntercept); }
        }
        private static bool Frame(IReadOnlyList<byte[]> a, int proto) { return a.Count == 1 && a[0] != null && a[0].Length == 6 && a[0][0] == 0 && a[0][1] == 6 && a[0][2] == 3 && a[0][3] == 232 && a[0][4] == (byte)(proto >> 8) && a[0][5] == (byte)(proto & 0xFF); }
    }
}
